# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
run:
  go: "1.24"
  timeout: 5m
linters:
  enable:
    - thelper
    - gosec
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo
    - tagliatelle
    - tagalign
    - misspell
    - depguard
  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: if-return
        - name: time-equal
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    forbidigo:
      forbid:
        - pattern: 'ioutil\.*'
    tagliatelle:
      case:
        use-field-name: false
        rules:
          yaml: snake
          json: snake
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/pkg/errors"
              desc: "use stdlib instead"
  exclusions:
    rules:
      - path: "cmd/scan_code.go"
        linters:
          - tagliatelle
      - path: "internal/phrase_sheet.go"
        # this should be entirely fine, since the seed is generated with crypto/rand
        text: "G404.*"
      - path: "internal/phrase_sheet/phrase_sheet.go"
        text: "G404.*"
      - # disable file inclusion via variable (gosec) here, it is a test file
        path: "cmd/decode_test.go"
        text: "G304:*"
      - # disable file inclusion via variable (gosec) here, it is intended that the user provide a file to read
        path: "internal/filesystem.go"
        text: "G304:*"

formatters:
  enable:
    - gofumpt
    - goimports
    - gci
    - golines
    - swaggo
