# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql

version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - task completions
    - task manpages

report_sizes: true

release:
  github:
    owner: tmuniversal
    name: papercrypt
  draft: false
  prerelease: auto

gomod:
  proxy: true

upx:
  - enabled: false
    compress: best
    lzma: true
    brute: false

builds:
  - id: papercrypt-amd64
    main: .
    binary: papercrypt
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    goarch:
      - amd64
    goos:
      - linux
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: &ldflags
      - -s -w -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}

  - id: papercrypt-arm64
    main: .
    binary: papercrypt
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
    goarch:
      - arm64
    goos:
      - linux
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: *ldflags

  - id: papercrypt-arm
    main: .
    binary: papercrypt
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
      - PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
    goarch:
      - arm
    goarm:
      - "7"
    goos:
      - linux
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: *ldflags

  - id: papercrypt-386
    main: .
    binary: papercrypt
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CGO_CFLAGS=-m32
      - CGO_LDFLAGS=-m32
      - PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
    goarch:
      - "386"
    goos:
      - linux
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: *ldflags

  - id: papercrypt-darwin
    main: .
    binary: papercrypt
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: *ldflags

  - id: papercrypt-windows
    main: .
    binary: papercrypt
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: *ldflags

universal_binaries:
  - replace: false

archives:
  - formats: [ "tar.gz" ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ "zip" ]
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - completions/*
      - manpages/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - cmd: cosign
    output: true
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args:
      - "sign-blob"
      - "--key=cosign.key"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args:
      - "sign"
      - "--key=cosign.key"
      - "${artifact}@${digest}"
      - "--yes"

homebrew_casks:
  - name: papercrypt
    skip_upload: auto
    repository:
      owner: tmuniversal
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_TOKEN }}"
    commit_author: &commit_author
      name: TMUniversal
      email: 10200399+TMUniversal@users.noreply.github.com
    homepage: &homepage https://github.com/TMUniversal/papercrypt
    description: &description A tool to generate paper backups of your passwords and other secrets.
    license: &license AGPL-3.0-or-later
    caveats: |
      To get started, run:
        papercrypt help
    manpages:
      - manpages/papercrypt.1.gz
    completions:
      bash: "completions/papercrypt.bash"
      fish: "completions/papercrypt.fish"
      zsh: "completions/papercrypt.zsh"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/papercrypt"]
          end
          
          system_command "#{staged_path}/papercrypt", args: ["version"]

scoops:
  - name: papercrypt
    skip_upload: auto
    repository:
      owner: tmuniversal
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_TOKEN }}"
    commit_author:
      <<: *commit_author
    homepage: *homepage
    description: *description
    license: *license
    shortcuts: [ [ "papercrypt.exe", "papercrypt" ] ]

blobs:
  - provider: s3
    endpoint: "{{.Env.S3_ENDPOINT}}"
    region: "{{.Env.S3_REGION}}"
    bucket: "{{.Env.S3_BUCKET}}"
    directory: "papercrypt/{{.Version}}"

dockers_v2:
  - images:
      - ghcr.io/tmuniversal/papercrypt
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64

sboms:
  - artifacts: archive
