version: "3"

tasks:
  generate:
    desc: Generate the code
    cmds:
      - go generate ./...
    generates:
      - "build_date.gen.txt"
      - "git_ref.gen.txt"
      - "git_commit.gen.txt"
      - "go_version.gen.txt"
      - "os_arch.gen.txt"
      - "os_type.gen.txt"
      - "version.gen.txt"
    sources:
      - "*.go"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".git/HEAD"
      - ".git/refs/heads/*"
      - ".git/refs/tags/*"
      - "scripts/*.sh"

  build:
    desc: Build the app
    deps:
      - generate
    sources:
      - "*.go"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "bin/papercrypt{{exeExt}}"
    cmds:
      - go build -v -o bin/papercrypt{{exeExt}} main.go

  test:
    desc: Run the tests
    deps:
      - build
    cmds:
      - go test -v ./... -cover
      - 'bin/papercrypt{{exeExt}} generate -i examples/input.json -o - --passphrase "example" --purpose "Example Sheet" --comment "Regular Text Output Example" | bin/papercrypt{{exeExt}} pdf2png | bin/papercrypt{{exeExt}} qr | bin/papercrypt{{exeExt}} decode -o examples/test.json -f --passphrase "example" && diff -u examples/input.json examples/test.json ; rm examples/test.json'

  examples:
    desc: Run the examples
    deps:
      - build
    generates:
      - "examples/output.txt"
      - "examples/armoured.txt"
      - "examples/lowercase.txt"
      - "examples/output.pdf"
      - "examples/no_qr.pdf"
      - "examples/armoured.pdf"
      - "examples/lowercase.pdf"
    cmds:
      - 'bin/papercrypt{{exeExt}} generate -i examples/input.json -o examples/output.pdf    --force --passphrase "example" --purpose "Example Sheet" --comment "Regular PDF Example"'
      - 'bin/papercrypt{{exeExt}} generate -i examples/input.json -o examples/no_qr.pdf     --force --passphrase "example" --purpose "Example Sheet" --comment "PDF without QR Code Example" --no-qr'
      - 'bin/papercrypt{{exeExt}} generate -i examples/input.json -o examples/lowercase.pdf --force --passphrase "example" --purpose "Example Sheet" --comment "Lowercase PDF Example" --lowercase'

  clean:
    desc: Remove all generated files
    cmds:
      - "rm -f *.gen.txt"
      - "rm -f bin/papercrypt{{exeExt}}"

  clean_examples:
    desc: Remove all generated files
    cmds:
      - "rm -f examples/output.txt examples/output.pdf examples/armoured.txt examples/armoured.pdf"
