version: "3"

tasks:
  generate:
    desc: Generate the code
    cmds:
      - go generate ./...
    generates:
      - "build_date.gen.txt"
      - "git_ref.gen.txt"
      - "git_commit.gen.txt"
      - "go_version.gen.txt"
      - "os_arch.gen.txt"
      - "os_type.gen.txt"
      - "version.gen.txt"
    sources:
      - "*.go"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".git/HEAD"
      - ".git/refs/heads/*"
      - ".git/refs/tags/*"
      - "scripts/*.sh"

  build:
    desc: Build the app
    deps:
      - generate
    sources:
      - "*.go"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "bin/papercrypt{{exeExt}}"
    cmds:
      - go build -v -o bin/papercrypt{{exeExt}} main.go

  test:
    desc: Run the tests
    deps:
      - build
    cmds:
      - go vet ./...
      - go test -v ./... -cover

  examples:
    desc: Run the examples
    deps:
      - build
      - deps:pdfcpu
    generates:
      - "examples/output.pdf"
      - "examples/no_qr.pdf"
      - "examples/lowercase.pdf"
      - "examples/phrase.pdf"
    cmds:
      - 'bin/papercrypt{{exeExt}} generate -i examples/input.json -o examples/output.pdf    --force --passphrase "example" --purpose "Example Sheet" --comment "Regular PDF Example"                 && pdfcpu validate -m strict examples/output.pdf'
      - 'bin/papercrypt{{exeExt}} generate -i examples/input.json -o examples/no_qr.pdf     --force --passphrase "example" --purpose "Example Sheet" --comment "PDF without QR Code Example" --no-qr && pdfcpu validate -m strict examples/no_qr.pdf'
      - 'bin/papercrypt{{exeExt}} generate -i examples/input.json -o examples/lowercase.pdf --force --passphrase "example" --purpose "Example Sheet" --comment "Lowercase PDF Example" --lowercase   && pdfcpu validate -m strict examples/lowercase.pdf'
      - 'bin/papercrypt{{exeExt}} phraseSheet -fo examples/phrase.pdf ExampleAbcA= && pdfcpu validate -m strict examples/phrase.pdf'

  man:
    desc: Generate man pages
    deps:
      - build
    cmds:
      - 'bin/papercrypt{{exeExt}} man'

  deps:pdfcpu:
    desc: Install pdfcpu
    internal: true
    cmds:
      - 'pdfcpu version || go install github.com/pdfcpu/pdfcpu/cmd/pdfcpu@latest && pdfcpu version'

  deps:goreleaser:
    desc: Install goreleaser
    internal: true
    cmds:
      - 'goreleaser --version || go install github.com/goreleaser/goreleaser@latest && goreleaser --version'

  clean:
    desc: Remove all generated files
    cmds:
      - "rm -f *.gen.txt"
      - "rm -rf dist bin man"

  clean:examples:
    desc: Remove all generated files
    cmds:
      - "rm -f examples/output.pdf examples/no_qr.pdf examples/lowercase.pdf examples/phrase.pdf"
