name: PaperCrypt Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Source checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: '**/*.sum'

      - name: Save `go version`
        id: go-version
        run: echo "GOVERSION=$(go version)" >> $GITHUB_OUTPUT

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v3
      - name: Confirm cosign installation
        run: cosign version

      - name: Install dependencies
        run: |
          sudo apt-get install -y poppler-utils upx
          which pdftoppm && which upx

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true

      - name: GitHub Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_KEY }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: Publish Release
        run: task release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          GORELEASER_TOKEN_TAP: ${{ secrets.GORELEASER_TOKEN_TAP }}
          GOVERSION: ${{ steps.go-version.outputs.GOVERSION }}
